
# Site settings
title: Guwen Han
name: Guwen Han
subtitle: PhD
email: guwenhan@zju.edu.cn
description: >
  PhD
baseurl: ""
url: "https://ligungun.github.io/guwenhan/"
github_username:  Guwen Han
disqus_baseurl: "https://ligungun.github.io/guwenhan/"
disqus_shortname: https-ligungun-github-io-guwenhan
permalink: :title
google-site-verification: ""

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Guwen Han"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: Guwen Han
    url: https://github.com/ligungun
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Guwen Han
    url: 
    desc: Connect with me on LinkedIn
    share: true
